# Generated by Django 5.1.2 on 2024-11-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', 'rename_price_to_uni_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
